# coding: utf-8

"""
    Flathub API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from flathub_python_api.api.collection_api import CollectionApi


class TestCollectionApi(unittest.TestCase):
    """CollectionApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CollectionApi()

    def tearDown(self) -> None:
        pass

    def test_get_categories_collection_category_get(self) -> None:
        """Test case for get_categories_collection_category_get

        Get Categories
        """
        pass

    def test_get_category_collection_category_category_get(self) -> None:
        """Test case for get_category_collection_category_category_get

        Get Category
        """
        pass

    def test_get_developer_collection_developer_developer_get(self) -> None:
        """Test case for get_developer_collection_developer_developer_get

        Get Developer
        """
        pass

    def test_get_developers_collection_developer_get(self) -> None:
        """Test case for get_developers_collection_developer_get

        Get Developers
        """
        pass

    def test_get_keyword_collection_keyword_get(self) -> None:
        """Test case for get_keyword_collection_keyword_get

        Get Keyword
        """
        pass

    def test_get_mobile_collection_mobile_get(self) -> None:
        """Test case for get_mobile_collection_mobile_get

        Get Mobile
        """
        pass

    def test_get_popular_last_month_collection_popular_get(self) -> None:
        """Test case for get_popular_last_month_collection_popular_get

        Get Popular Last Month
        """
        pass

    def test_get_recently_added_collection_recently_added_get(self) -> None:
        """Test case for get_recently_added_collection_recently_added_get

        Get Recently Added
        """
        pass

    def test_get_recently_updated_collection_recently_updated_get(self) -> None:
        """Test case for get_recently_updated_collection_recently_updated_get

        Get Recently Updated
        """
        pass

    def test_get_subcategory_collection_category_category_subcategories_get(self) -> None:
        """Test case for get_subcategory_collection_category_category_subcategories_get

        Get Subcategory
        """
        pass

    def test_get_trending_last_two_weeks_collection_trending_get(self) -> None:
        """Test case for get_trending_last_two_weeks_collection_trending_get

        Get Trending Last Two Weeks
        """
        pass

    def test_get_verified_collection_verified_get(self) -> None:
        """Test case for get_verified_collection_verified_get

        Get Verified
        """
        pass


if __name__ == '__main__':
    unittest.main()
