# coding: utf-8

"""
    Flathub API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.moderation_api import ModerationApi


class TestModerationApi(unittest.TestCase):
    """ModerationApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ModerationApi()

    def tearDown(self) -> None:
        pass

    def test_get_moderation_app_moderation_apps_app_id_get(self) -> None:
        """Test case for get_moderation_app_moderation_apps_app_id_get

        Get Moderation App
        """
        pass

    def test_get_moderation_apps_moderation_apps_get(self) -> None:
        """Test case for get_moderation_apps_moderation_apps_get

        Get Moderation Apps
        """
        pass

    def test_submit_review_moderation_requests_id_review_post(self) -> None:
        """Test case for submit_review_moderation_requests_id_review_post

        Submit Review
        """
        pass

    def test_submit_review_request_moderation_submit_review_request_post(self) -> None:
        """Test case for submit_review_request_moderation_submit_review_request_post

        Submit Review Request
        """
        pass


if __name__ == '__main__':
    unittest.main()
