# coding: utf-8

"""
    Flathub API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from flathub_python_api.models.main_category import MainCategory

class TestMainCategory(unittest.TestCase):
    """MainCategory unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMainCategory(self):
        """Test MainCategory"""
        # inst = MainCategory()

if __name__ == '__main__':
    unittest.main()
