# coding: utf-8

"""
    Flathub API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from flathub_python_api.models.available_login_method_status import AvailableLoginMethodStatus

class TestAvailableLoginMethodStatus(unittest.TestCase):
    """AvailableLoginMethodStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAvailableLoginMethodStatus(self):
        """Test AvailableLoginMethodStatus"""
        # inst = AvailableLoginMethodStatus()

if __name__ == '__main__':
    unittest.main()
