# coding: utf-8

"""
    Flathub API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from flathub_python_api.models.user_info import UserInfo

class TestUserInfo(unittest.TestCase):
    """UserInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserInfo:
        """Test UserInfo
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserInfo`
        """
        model = UserInfo()
        if include_optional:
            return UserInfo(
                displayname = '',
                dev_flatpaks = [
                    ''
                    ],
                permissions = [
                    'quality-moderation'
                    ],
                owned_flatpaks = [
                    ''
                    ],
                invited_flatpaks = [
                    ''
                    ],
                invite_code = '',
                accepted_publisher_agreement_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                default_account = flathub_python_api.models.auth_info.AuthInfo(
                    login = '', 
                    avatar = '', ),
                auths = flathub_python_api.models.auths.Auths(
                    github = flathub_python_api.models.auth_info.AuthInfo(
                        login = '', 
                        avatar = '', ), 
                    gitlab = flathub_python_api.models.auth_info.AuthInfo(
                        login = '', 
                        avatar = '', ), 
                    gnome = , 
                    kde = , )
            )
        else:
            return UserInfo(
                invite_code = '',
                accepted_publisher_agreement_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                default_account = flathub_python_api.models.auth_info.AuthInfo(
                    login = '', 
                    avatar = '', ),
                auths = flathub_python_api.models.auths.Auths(
                    github = flathub_python_api.models.auth_info.AuthInfo(
                        login = '', 
                        avatar = '', ), 
                    gitlab = flathub_python_api.models.auth_info.AuthInfo(
                        login = '', 
                        avatar = '', ), 
                    gnome = , 
                    kde = , ),
        )
        """

    def testUserInfo(self):
        """Test UserInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
