# coding: utf-8

"""
    Flathub API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.auth_api import AuthApi


class TestAuthApi(unittest.TestCase):
    """AuthApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AuthApi()

    def tearDown(self) -> None:
        pass

    def test_continue_github_flow_auth_login_github_post(self) -> None:
        """Test case for continue_github_flow_auth_login_github_post

        Continue Github Flow
        """
        pass

    def test_continue_gitlab_flow_auth_login_gitlab_post(self) -> None:
        """Test case for continue_gitlab_flow_auth_login_gitlab_post

        Continue Gitlab Flow
        """
        pass

    def test_continue_gnome_flow_auth_login_gnome_post(self) -> None:
        """Test case for continue_gnome_flow_auth_login_gnome_post

        Continue Gnome Flow
        """
        pass

    def test_continue_google_flow_auth_login_google_post(self) -> None:
        """Test case for continue_google_flow_auth_login_google_post

        Continue Google Flow
        """
        pass

    def test_continue_kde_flow_auth_login_kde_post(self) -> None:
        """Test case for continue_kde_flow_auth_login_kde_post

        Continue Kde Flow
        """
        pass

    def test_do_agree_to_publisher_agreement_auth_accept_publisher_agreement_post(self) -> None:
        """Test case for do_agree_to_publisher_agreement_auth_accept_publisher_agreement_post

        Do Agree To Publisher Agreement
        """
        pass

    def test_do_change_default_account_auth_change_default_account_post(self) -> None:
        """Test case for do_change_default_account_auth_change_default_account_post

        Do Change Default Account
        """
        pass

    def test_do_deleteuser_auth_deleteuser_post(self) -> None:
        """Test case for do_deleteuser_auth_deleteuser_post

        Do Deleteuser
        """
        pass

    def test_do_logout_auth_logout_post(self) -> None:
        """Test case for do_logout_auth_logout_post

        Do Logout
        """
        pass

    def test_do_refresh_dev_flatpaks_auth_refresh_dev_flatpaks_post(self) -> None:
        """Test case for do_refresh_dev_flatpaks_auth_refresh_dev_flatpaks_post

        Do Refresh Dev Flatpaks
        """
        pass

    def test_get_deleteuser_auth_deleteuser_get(self) -> None:
        """Test case for get_deleteuser_auth_deleteuser_get

        Get Deleteuser
        """
        pass

    def test_get_login_methods_auth_login_get(self) -> None:
        """Test case for get_login_methods_auth_login_get

        Get Login Methods
        """
        pass

    def test_get_userinfo_auth_userinfo_get(self) -> None:
        """Test case for get_userinfo_auth_userinfo_get

        Get Userinfo
        """
        pass

    def test_start_github_flow_auth_login_github_get(self) -> None:
        """Test case for start_github_flow_auth_login_github_get

        Start Github Flow
        """
        pass

    def test_start_gitlab_flow_auth_login_gitlab_get(self) -> None:
        """Test case for start_gitlab_flow_auth_login_gitlab_get

        Start Gitlab Flow
        """
        pass

    def test_start_gnome_flow_auth_login_gnome_get(self) -> None:
        """Test case for start_gnome_flow_auth_login_gnome_get

        Start Gnome Flow
        """
        pass

    def test_start_kde_flow_auth_login_kde_get(self) -> None:
        """Test case for start_kde_flow_auth_login_kde_get

        Start Kde Flow
        """
        pass


if __name__ == '__main__':
    unittest.main()
