# coding: utf-8

"""
    Flathub API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from flathub_python_api.api.app_picks_api import AppPicksApi


class TestAppPicksApi(unittest.TestCase):
    """AppPicksApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AppPicksApi()

    def tearDown(self) -> None:
        pass

    def test_get_app_of_the_day_app_picks_app_of_the_day_date_get(self) -> None:
        """Test case for get_app_of_the_day_app_picks_app_of_the_day_date_get

        Get App Of The Day
        """
        pass

    def test_get_app_of_the_week_app_picks_apps_of_the_week_date_get(self) -> None:
        """Test case for get_app_of_the_week_app_picks_apps_of_the_week_date_get

        Get App Of The Week
        """
        pass

    def test_set_app_of_the_day_app_picks_app_of_the_day_post(self) -> None:
        """Test case for set_app_of_the_day_app_picks_app_of_the_day_post

        Set App Of The Day
        """
        pass

    def test_set_app_of_the_week_app_picks_app_of_the_week_post(self) -> None:
        """Test case for set_app_of_the_week_app_picks_app_of_the_week_post

        Set App Of The Week
        """
        pass


if __name__ == '__main__':
    unittest.main()
