# coding: utf-8

"""
    Flathub API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from flathub_python_api.models.moderation_app_item import ModerationAppItem

class TestModerationAppItem(unittest.TestCase):
    """ModerationAppItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ModerationAppItem:
        """Test ModerationAppItem
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ModerationAppItem`
        """
        model = ModerationAppItem()
        if include_optional:
            return ModerationAppItem(
                appid = '',
                is_new_submission = True,
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                request_types = [
                    'appdata'
                    ]
            )
        else:
            return ModerationAppItem(
                appid = '',
                is_new_submission = True,
                request_types = [
                    'appdata'
                    ],
        )
        """

    def testModerationAppItem(self):
        """Test ModerationAppItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
