# coding: utf-8

"""
    Flathub API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.vending_redirect import VendingRedirect

class TestVendingRedirect(unittest.TestCase):
    """VendingRedirect unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VendingRedirect:
        """Test VendingRedirect
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VendingRedirect`
        """
        model = VendingRedirect()
        if include_optional:
            return VendingRedirect(
                status = '',
                target_url = ''
            )
        else:
            return VendingRedirect(
                status = '',
                target_url = '',
        )
        """

    def testVendingRedirect(self):
        """Test VendingRedirect"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
