# coding: utf-8

"""
    Flathub API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from flathub_python_api.models.upsert_app_of_the_week import UpsertAppOfTheWeek

class TestUpsertAppOfTheWeek(unittest.TestCase):
    """UpsertAppOfTheWeek unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpsertAppOfTheWeek:
        """Test UpsertAppOfTheWeek
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpsertAppOfTheWeek`
        """
        model = UpsertAppOfTheWeek()
        if include_optional:
            return UpsertAppOfTheWeek(
                app_id = '',
                week_number = 56,
                year = 56,
                position = 56
            )
        else:
            return UpsertAppOfTheWeek(
                app_id = '',
                week_number = 56,
                year = 56,
                position = 56,
        )
        """

    def testUpsertAppOfTheWeek(self):
        """Test UpsertAppOfTheWeek"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
