# coding: utf-8

"""
    Flathub API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.available_method import AvailableMethod

class TestAvailableMethod(unittest.TestCase):
    """AvailableMethod unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AvailableMethod:
        """Test AvailableMethod
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AvailableMethod`
        """
        model = AvailableMethod()
        if include_optional:
            return AvailableMethod(
                method = 'website',
                website = '',
                website_token = '',
                login_provider = 'github',
                login_name = '',
                login_is_organization = True,
                login_status = 'ready'
            )
        else:
            return AvailableMethod(
                method = 'website',
        )
        """

    def testAvailableMethod(self):
        """Test AvailableMethod"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
