# coding: utf-8

"""
    Flathub API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.quality_moderation_type import QualityModerationType

class TestQualityModerationType(unittest.TestCase):
    """QualityModerationType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> QualityModerationType:
        """Test QualityModerationType
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `QualityModerationType`
        """
        model = QualityModerationType()
        if include_optional:
            return QualityModerationType(
                guideline_id = '',
                guideline = openapi_client.models.guideline.Guideline(
                    id = '', 
                    url = '', 
                    needed_to_pass_since = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    category = '', 
                    read_only = True, ),
                app_id = '',
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_by = 56,
                passed = True,
                comment = '',
                needed_to_pass_since = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return QualityModerationType(
                guideline_id = '',
                guideline = openapi_client.models.guideline.Guideline(
                    id = '', 
                    url = '', 
                    needed_to_pass_since = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    category = '', 
                    read_only = True, ),
                app_id = '',
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_by = 56,
                passed = True,
                comment = '',
                needed_to_pass_since = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )
        """

    def testQualityModerationType(self):
        """Test QualityModerationType"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
