# coding: utf-8

"""
    Flathub API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.verification_method import VerificationMethod

class TestVerificationMethod(unittest.TestCase):
    """VerificationMethod unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVerificationMethod(self):
        """Test VerificationMethod"""
        # inst = VerificationMethod()

if __name__ == '__main__':
    unittest.main()
