# coding: utf-8

"""
    Flathub API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.feed_api import FeedApi


class TestFeedApi(unittest.TestCase):
    """FeedApi unit test stubs"""

    def setUp(self) -> None:
        self.api = FeedApi()

    def tearDown(self) -> None:
        pass

    def test_get_new_apps_feed_feed_new_get(self) -> None:
        """Test case for get_new_apps_feed_feed_new_get

        Get New Apps Feed
        """
        pass

    def test_get_recently_updated_apps_feed_feed_recently_updated_get(self) -> None:
        """Test case for get_recently_updated_apps_feed_feed_recently_updated_get

        Get Recently Updated Apps Feed
        """
        pass


if __name__ == '__main__':
    unittest.main()
