# coding: utf-8

"""
    Flathub API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from flathub_python_api.models.app_routes_invites_developers_response import AppRoutesInvitesDevelopersResponse

class TestAppRoutesInvitesDevelopersResponse(unittest.TestCase):
    """AppRoutesInvitesDevelopersResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AppRoutesInvitesDevelopersResponse:
        """Test AppRoutesInvitesDevelopersResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AppRoutesInvitesDevelopersResponse`
        """
        model = AppRoutesInvitesDevelopersResponse()
        if include_optional:
            return AppRoutesInvitesDevelopersResponse(
                developers = [
                    flathub_python_api.models.developer.Developer(
                        id = 56, 
                        is_self = True, 
                        name = '', 
                        is_primary = True, )
                    ],
                invites = [
                    flathub_python_api.models.developer.Developer(
                        id = 56, 
                        is_self = True, 
                        name = '', 
                        is_primary = True, )
                    ]
            )
        else:
            return AppRoutesInvitesDevelopersResponse(
                developers = [
                    flathub_python_api.models.developer.Developer(
                        id = 56, 
                        is_self = True, 
                        name = '', 
                        is_primary = True, )
                    ],
                invites = [
                    flathub_python_api.models.developer.Developer(
                        id = 56, 
                        is_self = True, 
                        name = '', 
                        is_primary = True, )
                    ],
        )
        """

    def testAppRoutesInvitesDevelopersResponse(self):
        """Test AppRoutesInvitesDevelopersResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
