# coding: utf-8

"""
    Flathub API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.transaction_sort_order import TransactionSortOrder

class TestTransactionSortOrder(unittest.TestCase):
    """TransactionSortOrder unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTransactionSortOrder(self):
        """Test TransactionSortOrder"""
        # inst = TransactionSortOrder()

if __name__ == '__main__':
    unittest.main()
