# coding: utf-8

"""
    Flathub API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from flathub_python_api.models.app_search_developers_response import AppSearchDevelopersResponse

class TestAppSearchDevelopersResponse(unittest.TestCase):
    """AppSearchDevelopersResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AppSearchDevelopersResponse:
        """Test AppSearchDevelopersResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AppSearchDevelopersResponse`
        """
        model = AppSearchDevelopersResponse()
        if include_optional:
            return AppSearchDevelopersResponse(
                developers = [
                    ''
                    ],
                total = 56,
                page = 56,
                per_page = 56
            )
        else:
            return AppSearchDevelopersResponse(
                developers = [
                    ''
                    ],
                total = 56,
                page = 56,
                per_page = 56,
        )
        """

    def testAppSearchDevelopersResponse(self):
        """Test AppSearchDevelopersResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
