# coding: utf-8

"""
    Flathub API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from flathub_python_api.models.meilisearch_response_limited_apps_index import MeilisearchResponseLimitedAppsIndex

class TestMeilisearchResponseLimitedAppsIndex(unittest.TestCase):
    """MeilisearchResponseLimitedAppsIndex unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MeilisearchResponseLimitedAppsIndex:
        """Test MeilisearchResponseLimitedAppsIndex
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MeilisearchResponseLimitedAppsIndex`
        """
        model = MeilisearchResponseLimitedAppsIndex()
        if include_optional:
            return MeilisearchResponseLimitedAppsIndex(
                hits = [
                    flathub_python_api.models.apps_index.AppsIndex(
                        name = '', 
                        keywords = [
                            ''
                            ], 
                        summary = '', 
                        description = '', 
                        id = '', 
                        type = '', 
                        translations = {
                            'key' : {
                                'key' : ''
                                }
                            }, 
                        project_license = '', 
                        is_free_license = True, 
                        app_id = '', 
                        icon = '', 
                        main_categories = null, 
                        sub_categories = [
                            ''
                            ], 
                        developer_name = '', 
                        verification_verified = True, 
                        verification_method = 'none', 
                        verification_login_name = '', 
                        verification_login_provider = '', 
                        verification_login_is_organization = '', 
                        verification_website = '', 
                        verification_timestamp = '', 
                        runtime = '', 
                        updated_at = 56, 
                        arches = [
                            ''
                            ], 
                        added_at = 56, 
                        trending = 1.337, 
                        installs_last_month = 56, 
                        is_mobile_friendly = True, )
                    ],
                query = '',
                processing_time_ms = 56,
                limit = 56,
                offset = 56,
                estimated_total_hits = 56,
                facet_distribution = {
                    'key' : {
                        'key' : 56
                        }
                    },
                facet_stats = {
                    'key' : {
                        'key' : 56
                        }
                    }
            )
        else:
            return MeilisearchResponseLimitedAppsIndex(
                hits = [
                    flathub_python_api.models.apps_index.AppsIndex(
                        name = '', 
                        keywords = [
                            ''
                            ], 
                        summary = '', 
                        description = '', 
                        id = '', 
                        type = '', 
                        translations = {
                            'key' : {
                                'key' : ''
                                }
                            }, 
                        project_license = '', 
                        is_free_license = True, 
                        app_id = '', 
                        icon = '', 
                        main_categories = null, 
                        sub_categories = [
                            ''
                            ], 
                        developer_name = '', 
                        verification_verified = True, 
                        verification_method = 'none', 
                        verification_login_name = '', 
                        verification_login_provider = '', 
                        verification_login_is_organization = '', 
                        verification_website = '', 
                        verification_timestamp = '', 
                        runtime = '', 
                        updated_at = 56, 
                        arches = [
                            ''
                            ], 
                        added_at = 56, 
                        trending = 1.337, 
                        installs_last_month = 56, 
                        is_mobile_friendly = True, )
                    ],
                query = '',
                processing_time_ms = 56,
                limit = 56,
                offset = 56,
                estimated_total_hits = 56,
        )
        """

    def testMeilisearchResponseLimitedAppsIndex(self):
        """Test MeilisearchResponseLimitedAppsIndex"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
