# coding: utf-8

"""
    Flathub API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from flathub_python_api.api.compat_api import CompatApi


class TestCompatApi(unittest.TestCase):
    """CompatApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CompatApi()

    def tearDown(self) -> None:
        pass

    def test_get_popular_apps_compat_apps_collection_popular50_get(self) -> None:
        """Test case for get_popular_apps_compat_apps_collection_popular50_get

        Get Popular Apps
        """
        pass

    def test_get_popular_apps_compat_apps_collection_popular_get(self) -> None:
        """Test case for get_popular_apps_compat_apps_collection_popular_get

        Get Popular Apps
        """
        pass

    def test_get_recently_added_compat_apps_collection_new25_get(self) -> None:
        """Test case for get_recently_added_compat_apps_collection_new25_get

        Get Recently Added
        """
        pass

    def test_get_recently_added_compat_apps_collection_new_get(self) -> None:
        """Test case for get_recently_added_compat_apps_collection_new_get

        Get Recently Added
        """
        pass

    def test_get_recently_updated_compat_apps_collection_recently_updated25_get(self) -> None:
        """Test case for get_recently_updated_compat_apps_collection_recently_updated25_get

        Get Recently Updated
        """
        pass

    def test_get_recently_updated_compat_apps_collection_recently_updated_get(self) -> None:
        """Test case for get_recently_updated_compat_apps_collection_recently_updated_get

        Get Recently Updated
        """
        pass

    def test_get_search_compat_apps_search_query_get(self) -> None:
        """Test case for get_search_compat_apps_search_query_get

        Get Search
        """
        pass

    def test_get_single_app_compat_apps_app_id_get(self) -> None:
        """Test case for get_single_app_compat_apps_app_id_get

        Get Single App
        """
        pass


if __name__ == '__main__':
    unittest.main()
