# coding: utf-8

"""
    Flathub API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from flathub_python_api.api.users_api import UsersApi


class TestUsersApi(unittest.TestCase):
    """UsersApi unit test stubs"""

    def setUp(self) -> None:
        self.api = UsersApi()

    def tearDown(self) -> None:
        pass

    def test_add_user_role_users_user_id_role_post(self) -> None:
        """Test case for add_user_role_users_user_id_role_post

        Add User Role
        """
        pass

    def test_delete_user_role_users_user_id_role_delete(self) -> None:
        """Test case for delete_user_role_users_user_id_role_delete

        Delete User Role
        """
        pass

    def test_role_users_users_roles_role_name_get(self) -> None:
        """Test case for role_users_users_roles_role_name_get

        Role Users
        """
        pass

    def test_roles_users_roles_get(self) -> None:
        """Test case for roles_users_roles_get

        Roles
        """
        pass

    def test_user_users_user_id_get(self) -> None:
        """Test case for user_users_user_id_get

        User
        """
        pass

    def test_users_users_get(self) -> None:
        """Test case for users_users_get

        Users
        """
        pass


if __name__ == '__main__':
    unittest.main()
