# coding: utf-8

"""
    Flathub API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from flathub_python_api.models.quality_moderation_status import QualityModerationStatus
from typing import Optional, Set
from typing_extensions import Self

class QualityModerationDashboardRow(BaseModel):
    """
    QualityModerationDashboardRow
    """ # noqa: E501
    id: StrictStr
    quality_moderation_status: QualityModerationStatus
    appstream: Optional[Any] = None
    installs_last_7_days: Optional[StrictInt] = None
    __properties: ClassVar[List[str]] = ["id", "quality_moderation_status", "appstream", "installs_last_7_days"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of QualityModerationDashboardRow from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of quality_moderation_status
        if self.quality_moderation_status:
            _dict['quality_moderation_status'] = self.quality_moderation_status.to_dict()
        # override the default output from pydantic by calling `to_dict()` of appstream
        if self.appstream:
            _dict['appstream'] = self.appstream.to_dict()
        # set to None if appstream (nullable) is None
        # and model_fields_set contains the field
        if self.appstream is None and "appstream" in self.model_fields_set:
            _dict['appstream'] = None

        # set to None if installs_last_7_days (nullable) is None
        # and model_fields_set contains the field
        if self.installs_last_7_days is None and "installs_last_7_days" in self.model_fields_set:
            _dict['installs_last_7_days'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of QualityModerationDashboardRow from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "quality_moderation_status": QualityModerationStatus.from_dict(obj["quality_moderation_status"]) if obj.get("quality_moderation_status") is not None else None,
            "appstream": AnyOf.from_dict(obj["appstream"]) if obj.get("appstream") is not None else None,
            "installs_last_7_days": obj.get("installs_last_7_days")
        })
        return _obj


